name: ham-flow
channels:
  - conda-forge
dependencies:
  - python=3.9.12
  - pip=22.0.4
  - pandas=1.4.2
  - sf-hamilton=1.7.0
  - metaflow=2.6.1
  - numpy=1.22.3
  - scikit-learn=1.0.2
  - skrebate=0.62
  - matplotlib=3.5.1
  - xgboost=1.5.1
  - python-graphviz=0.8.4